### ISSUE TITLE
I'm pretty sure I'm doing something wrong could you help me out

### ISSUE THREAD

**Issue by xenomorphgourmet** [Anirataaak/OrnaRPGBot#4]
[ WARN:0@0.281] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('bot\rsc\inn.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\xenom\Downloads\OrnaRPGBot-1.2.1\OrnaRPGBot-1.2.1\bot\scripts\OrnaRPGBot.py", line 22, in <module>
    actions.heal(fightCount, countToHeal)
  File "C:\Users\xenom\Downloads\OrnaRPGBot-1.2.1\OrnaRPGBot-1.2.1\bot\scripts\actions.py", line 9, in heal
    _inn_ = locate.locateInn()
  File "C:\Users\xenom\Downloads\OrnaRPGBot-1.2.1\OrnaRPGBot-1.2.1\bot\scripts\locate.py", line 5, in locateInn
    _inn_ = pyautogui.locateOnScreen(r'bot\rsc\inn.png', confidence=0.6)
  File "C:\Users\xenom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\xenom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyautogui\__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
  File "C:\Users\xenom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyscreeze\__init__.py", line 373, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "C:\Users\xenom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyscreeze\__init__.py", line 353, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\Users\xenom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyscreeze\__init__.py", line 207, in _locateAll_opencv
    needleImage = _load_cv2(needleImage, grayscale)
  File "C:\Users\xenom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyscreeze\__init__.py", line 170, in _load_cv2
    raise IOError("Failed to read %s because file is missing, "
OSError: Failed to read bot\rsc\inn.png because file is missing, has improper permissions, or is an unsupported or invalid format

Process finished with exit code 1

**Comment by xenomorphgourmet** [comment]
I've got absolutely no idea no idea on what I'm doing and but I'm certain I'm doing something wrong

**Comment by Anirataaak** [comment]
Hey, sorry for the very late reply. Does the problem still exist? I am working on a new version right now. But if the problem still exists I would look at this, that this also does not happen in the new version :)

**Comment by xenomorphgourmet** [comment]
Well for some reason I cant seem to recreate the error but this keeps coming.
![Screenshot 2022-04-28 191413](https://user-images.githubusercontent.com/55250166/165862495-cd7231a3-0d94-41fd-8a8b-c65e4f2eb45c.png)
Like I said before this could 100% be operator error and have little to nothing to do with your code.

**Comment by Anirataaak** [comment]
It looks like you didn't set up the workspace properly. You have the OrnaRPGBot... folder twice. You have to open the project from the folder where the .idea folder is. Otherwise the correct path to the resources will not be recognized. This should have changed in the new version anyway. But currently this should solve your problem :)
